" Name:         Gruvbox Material Hard
" Description:  Gruvbox with Material Palette
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/gruvbox-material/
" License:      MIT && Anti-996
" Last Updated: Thu 15 Aug 2019 10:52:05 AM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'gruvbox-material-hard'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

let s:italics = !(get(g:, 'gruvbox_material_kill_italic', 0) && s:italics)
hi! link markdownCodeDelimiter Aqua
hi! link markdownBoldDelimiter Grey
hi! link markdownLinkText Purple
hi! link markdownHeadingDelimiter Grey
hi! link markdownListMarker Red
hi! link markdownOrderedListMarker Red
hi! link markdownRule Purple
hi! link markdownHeadingRule Purple
hi! link markdownId Yellow
hi! link mkdCodeDelimiter Aqua
hi! link mkdBold Grey
hi! link mkdLink Purple
hi! link mkdHeading Grey
hi! link mkdListItem Red
hi! link mkdRule Purple
hi! link mkdDelimiter Grey
hi! link mkdId Yellow
hi! link rstSubstitutionReference Blue
hi! link rstInterpretedTextOrHyperlinkReference Aqua
hi! link rstTableLines Grey
hi! link texStatement Green
hi! link texOnlyMath Grey
hi! link texDefName Yellow
hi! link texNewCmd Orange
hi! link texCmdName Blue
hi! link texBeginEnd Red
hi! link texBeginEndName Blue
hi! link texDocType Orange
hi! link htmlTag Orange
hi! link htmlEndTag Yellow
hi! link htmlTagName Orange
hi! link htmlArg Aqua
hi! link htmlScriptTag Purple
hi! link htmlSpecialTagName Blue
hi! link xmlTag Orange
hi! link xmlEndTag Yellow
hi! link xmlTagName Orange
hi! link xmlEqual Orange
hi! link xmlAttrib Aqua
hi! link xmlEntity Red
hi! link xmlEntityPunct Red
hi! link xmlDocTypeDecl Grey
hi! link xmlDocTypeKeyword Purple
hi! link xmlCdataStart Grey
hi! link xmlCdataCdata Purple
hi! link cssAttrComma White
hi! link cssBraces White
hi! link cssTagName Purple
hi! link cssClassNameDot Red
hi! link cssClassName Red
hi! link cssFunctionName Yellow
hi! link cssAttr Orange
hi! link cssProp Aqua
hi! link cssCommonAttr Yellow
hi! link cssPseudoClassId Blue
hi! link cssPseudoClassFn Green
hi! link cssPseudoClass Purple
hi! link cssImportant Red
hi! link cssSelectorOp Orange
hi! link cssSelectorOp2 Orange
hi! link cssColor Green
hi! link cssAttributeSelector Aqua
hi! link cssUnitDecorators Orange
hi! link cssNoise Grey
hi! link sassProperty Green
hi! link sassAmpersand Orange
hi! link sassClass Red
hi! link sassClassChar Red
hi! link sassMixing Green
hi! link sassMixinName Orange
hi! link sassCssAttribute Yellow
hi! link sassInterpolationDelimiter Green
hi! link sassFunction Yellow
hi! link sassControl Red
hi! link scssSelectorName Red
hi! link scssSelectorChar Red
hi! link scssForKeyword Purple
hi! link scssAttribute Orange
hi! link scssInterpolationDelimiter Green
hi! link scssMixinName Yellow
hi! link scssFunctionName Yellow
hi! link lessMixinChar Grey
hi! link lessClass Red
hi! link lessVariable Blue
hi! link lessAmpersandChar Orange
hi! link lessFunction Yellow
hi! link javaScriptFunction Aqua
hi! link javaScriptOperator Red
hi! link javaScriptIdentifier Orange
hi! link javaScriptMember Blue
hi! link javaScriptNull Yellow
hi! link javaScriptParens White
hi! link javaScriptBraces White
hi! link javascriptEndColons White
hi! link javascriptVariable Orange
hi! link javascriptIdentifierName Blue
hi! link javascriptObjectLabel White
hi! link javascriptPropertyNameString Green
hi! link javascriptFuncArg Green
hi! link javascriptFuncCallArg White
hi! link javascriptOpSymbol Orange
hi! link javascriptOpSymbols Orange
hi! link javascriptGlobal Yellow
hi! link javascriptNodeGlobal Purple
hi! link javascriptDotNotation Grey
hi! link javascriptBrackets White
hi! link javascriptMethodAccessor Red
hi! link javascriptMethodAccessorWords Red
hi! link javascriptMethod Green
hi! link javascriptMethodName Green
hi! link javascriptObjectMethodName Green
hi! link javascriptDOMStorageMethod Green
hi! link javascriptFileMethod Green
hi! link javascriptFileReaderMethod Green
hi! link javascriptFileListMethod Green
hi! link javascriptBlobMethod Green
hi! link javascriptURLStaticMethod Green
hi! link javascriptNumberStaticMethod Green
hi! link javascriptNumberMethod Green
hi! link javascriptDOMNodeMethod Green
hi! link javascriptES6BigIntStaticMethod Green
hi! link javascriptBOMWindowMethod Green
hi! link javascriptHeadersMethod Green
hi! link javascriptRequestMethod Green
hi! link javascriptResponseMethod Green
hi! link javascriptES6SetMethod Green
hi! link javascriptReflectMethod Green
hi! link javascriptPaymentMethod Green
hi! link javascriptPaymentResponseMethod Green
hi! link javascriptTypedArrayStaticMethod Green
hi! link javascriptGeolocationMethod Green
hi! link javascriptES6MapMethod Green
hi! link javascriptServiceWorkerMethod Green
hi! link javascriptCacheMethod Green
hi! link javascriptFunctionMethod Green
hi! link javascriptXHRMethod Green
hi! link javascriptBOMNavigatorMethod Green
hi! link javascriptServiceWorkerMethod Green
hi! link javascriptDOMEventTargetMethod Green
hi! link javascriptDOMEventMethod Green
hi! link javascriptIntlMethod Green
hi! link javascriptDOMDocMethod Green
hi! link javascriptStringStaticMethod Green
hi! link javascriptStringMethod Green
hi! link javascriptSymbolStaticMethod Green
hi! link javascriptRegExpMethod Green
hi! link javascriptObjectStaticMethod Green
hi! link javascriptObjectMethod Green
hi! link javascriptBOMLocationMethod Green
hi! link javascriptJSONStaticMethod Green
hi! link javascriptGeneratorMethod Green
hi! link javascriptEncodingMethod Green
hi! link javascriptPromiseStaticMethod Green
hi! link javascriptPromiseMethod Green
hi! link javascriptBOMHistoryMethod Green
hi! link javascriptDOMFormMethod Green
hi! link javascriptClipboardMethod Green
hi! link javascriptTypedArrayStaticMethod Green
hi! link javascriptBroadcastMethod Green
hi! link javascriptDateStaticMethod Green
hi! link javascriptDateMethod Green
hi! link javascriptConsoleMethod Green
hi! link javascriptArrayStaticMethod Green
hi! link javascriptArrayMethod Green
hi! link javascriptMathStaticMethod Green
hi! link javascriptSubtleCryptoMethod Green
hi! link javascriptCryptoMethod Green
hi! link javascriptGlobalMethod Aqua
hi! link javascriptBOMWindowProp Aqua
hi! link javascriptDOMStorageProp Aqua
hi! link javascriptFileReaderProp Aqua
hi! link javascriptURLUtilsProp Aqua
hi! link javascriptNumberStaticProp Aqua
hi! link javascriptDOMNodeProp Aqua
hi! link javascriptRequestProp Aqua
hi! link javascriptResponseProp Aqua
hi! link javascriptES6SetProp Aqua
hi! link javascriptPaymentProp Aqua
hi! link javascriptPaymentResponseProp Aqua
hi! link javascriptPaymentAddressProp Aqua
hi! link javascriptPaymentShippingOptionProp Aqua
hi! link javascriptTypedArrayStaticProp Aqua
hi! link javascriptServiceWorkerProp Aqua
hi! link javascriptES6MapProp Aqua
hi! link javascriptRegExpStaticProp Aqua
hi! link javascriptRegExpProp Aqua
hi! link javascriptXHRProp Aqua
hi! link javascriptBOMNavigatorProp Aqua
hi! link javascriptDOMEventProp Aqua
hi! link javascriptBOMNetworkProp Aqua
hi! link javascriptDOMDocProp Aqua
hi! link javascriptSymbolStaticProp Aqua
hi! link javascriptSymbolProp Aqua
hi! link javascriptBOMLocationProp Aqua
hi! link javascriptEncodingProp Aqua
hi! link javascriptCryptoProp Aqua
hi! link javascriptBOMHistoryProp Aqua
hi! link javascriptDOMFormProp Aqua
hi! link javascriptDataViewProp Aqua
hi! link javascriptBroadcastProp Aqua
hi! link javascriptMathStaticProp Aqua
hi! link jsFunction Red
hi! link jsThis Yellow
hi! link jsGlobalNodeObjects Purple
hi! link jsGlobalObjects Yellow
hi! link jsArrowFunction Purple
hi! link jsObjectProp Aqua
hi! link jsVariableDef Blue
hi! link jsBlockLabel Orange
hi! link jsFrom Red
hi! link jsModuleKeyword Aqua
hi! link jsFuncArgs Green
hi! link jsFuncCall Green
hi! link jsObjectValue Green
hi! link typescriptBraces White
hi! link typescriptEndColons White
hi! link typescriptParens White
hi! link typescriptStatement Red
hi! link typescriptGlobalObjects Purple
hi! link typescriptNull Aqua
hi! link typescriptOperator Orange
hi! link typescriptInterpolation Aqua
hi! link typescriptInterpolationDelimiter Aqua
hi! link typescriptExceptions Red
hi! link typescriptImport Purple
hi! link typescriptBOM Aqua
hi! link typescriptVariable Orange
hi! link typescriptVariableDeclaration Blue
hi! link typescriptAssign Orange
hi! link typescriptExport Purple
hi! link typescriptAliasDeclaration Aqua
hi! link typescriptDefault Orange
hi! link typescriptReadonlyModifier Orange
hi! link typescriptIdentifier Blue
hi! link typescriptArrowFunc Aqua
hi! link typescriptBinaryOp Orange
hi! link typescriptFuncComma White
hi! link typescriptFuncArg Green
hi! link typescriptFuncCallArg White
hi! link typescriptClassName Orange
hi! link typescriptClassHeritage Orange
hi! link typescriptEnum Aqua
hi! link typescriptArrowFuncArg Aqua
hi! link typescriptBOMNavigatorProp Aqua
hi! link typescriptOptionalMark Orange
hi! link typescriptCase Orange
hi! link typescriptTypeParameter Yellow
hi! link typescriptCastKeyword Orange
hi! link typescriptTypeReference Purple
hi! link typescriptGlobal Purple
hi! link typescriptObjectLabel Orange
hi! link typescriptDotNotation Grey
hi! link typescriptCall Blue
hi! link typescriptTemplateSubstitution Blue
hi! link typescriptTemplateSB Aqua
hi! link typescriptUnaryOp Orange
hi! link typescriptMethodAccessor Orange
hi! link typescriptGlobalMethod Aqua
hi! link typescriptDOMStorageMethod Green
hi! link typescriptFileMethod Green
hi! link typescriptFileReaderMethod Green
hi! link typescriptFileListMethod Green
hi! link typescriptBlobMethod Green
hi! link typescriptURLStaticMethod Green
hi! link typescriptNumberStaticMethod Green
hi! link typescriptNumberMethod Green
hi! link typescriptDOMNodeMethod Green
hi! link typescriptPaymentMethod Green
hi! link typescriptPaymentResponseMethod Green
hi! link typescriptHeadersMethod Green
hi! link typescriptRequestMethod Green
hi! link typescriptResponseMethod Green
hi! link typescriptES6SetMethod Green
hi! link typescriptReflectMethod Green
hi! link typescriptBOMWindowMethod Green
hi! link typescriptGeolocationMethod Green
hi! link typescriptServiceWorkerMethod Green
hi! link typescriptCacheMethod Green
hi! link typescriptES6MapMethod Green
hi! link typescriptFunctionMethod Green
hi! link typescriptRegExpMethod Green
hi! link typescriptXHRMethod Green
hi! link typescriptBOMNavigatorMethod Green
hi! link typescriptServiceWorkerMethod Green
hi! link typescriptIntlMethod Green
hi! link typescriptDOMEventTargetMethod Green
hi! link typescriptDOMEventMethod Green
hi! link typescriptDOMDocMethod Green
hi! link typescriptStringStaticMethod Green
hi! link typescriptStringMethod Green
hi! link typescriptSymbolStaticMethod Green
hi! link typescriptObjectStaticMethod Green
hi! link typescriptObjectMethod Green
hi! link typescriptJSONStaticMethod Green
hi! link typescriptEncodingMethod Green
hi! link typescriptBOMLocationMethod Green
hi! link typescriptPromiseStaticMethod Green
hi! link typescriptPromiseMethod Green
hi! link typescriptSubtleCryptoMethod Green
hi! link typescriptCryptoMethod Green
hi! link typescriptBOMHistoryMethod Green
hi! link typescriptDOMFormMethod Green
hi! link typescriptConsoleMethod Green
hi! link typescriptDateStaticMethod Green
hi! link typescriptDateMethod Green
hi! link typescriptArrayStaticMethod Green
hi! link typescriptArrayMethod Green
hi! link typescriptMathStaticMethod Green
hi! link typescriptStringProperty Aqua
hi! link typescriptDOMStorageProp Aqua
hi! link typescriptFileReaderProp Aqua
hi! link typescriptURLUtilsProp Aqua
hi! link typescriptNumberStaticProp Aqua
hi! link typescriptDOMNodeProp Aqua
hi! link typescriptBOMWindowProp Aqua
hi! link typescriptRequestProp Aqua
hi! link typescriptResponseProp Aqua
hi! link typescriptPaymentProp Aqua
hi! link typescriptPaymentResponseProp Aqua
hi! link typescriptPaymentAddressProp Aqua
hi! link typescriptPaymentShippingOptionProp Aqua
hi! link typescriptES6SetProp Aqua
hi! link typescriptServiceWorkerProp Aqua
hi! link typescriptES6MapProp Aqua
hi! link typescriptRegExpStaticProp Aqua
hi! link typescriptRegExpProp Aqua
hi! link typescriptBOMNavigatorProp Aqua
hi! link typescriptXHRProp Aqua
hi! link typescriptDOMEventProp Aqua
hi! link typescriptDOMDocProp Aqua
hi! link typescriptBOMNetworkProp Aqua
hi! link typescriptSymbolStaticProp Aqua
hi! link typescriptEncodingProp Aqua
hi! link typescriptBOMLocationProp Aqua
hi! link typescriptCryptoProp Aqua
hi! link typescriptDOMFormProp Aqua
hi! link typescriptBOMHistoryProp Aqua
hi! link typescriptMathStaticProp Aqua
hi! link dartTypedef Red
hi! link dartType Red
hi! link dartKeyword Aqua
hi! link dartCoreClasses Yellow
hi! link dartInterpolation Blue
hi! link coffeeExtendedOp Orange
hi! link coffeeSpecialOp White
hi! link coffeeDotAccess Grey
hi! link coffeeCurly White
hi! link coffeeParen White
hi! link coffeeBracket White
hi! link coffeeCurlies Aqua
hi! link coffeeParens Blue
hi! link coffeeBrackets Green
hi! link coffeeOperator Red
hi! link coffeeInterp Purple
hi! link coffeeStatement Orange
hi! link coffeeSpecialIdent Purple
hi! link purescriptModuleKeyword Purple
hi! link purescriptModule Aqua
hi! link purescriptModuleParams Blue
hi! link purescriptAsKeyword Orange
hi! link purescriptHidingKeyword Orange
hi! link purescriptWhere Orange
hi! link pythonBuiltin Aqua
hi! link pythonBuiltinType Yellow
hi! link pythonBuiltinObj Purple
hi! link pythonBuiltinFunc Green
hi! link pythonExClass Purple
hi! link pythonFunction Aqua
hi! link pythonDecorator Orange
hi! link pythonInclude Include
hi! link pythonImport PreProc
hi! link pythonRun Blue
hi! link pythonCoding Blue
hi! link pythonOperator Orange
hi! link pythonException Red
hi! link pythonExceptions Purple
hi! link pythonConditional Red
hi! link pythonRepeat Red
hi! link pythonNone Yellow
hi! link pythonDot Grey
hi! link javaAnnotation Aqua
hi! link javaParen White
hi! link javaParen1 White
hi! link javaParen2 White
hi! link javaParen3 White
hi! link javaParen4 White
hi! link javaParen5 White
hi! link javaOperator Orange
hi! link javaVarArg Green
hi! link javaClassDecl Red
hi! link javaMethodDecl Red
hi! link ktStructure Red
hi! link ktAnnotation Aqua
hi! link ktKeyword Blue
hi! link ktComplexInterpolation Blue
hi! link ktComplexInterpolationBrace Aqua
hi! link goPackage Purple
hi! link goImport Purple
hi! link goDeclType Orange
hi! link goBuiltins Aqua
hi! link goPredefinedIdentifiers Blue
hi! link rustModPath Aqua
hi! link rustModPathSep Grey
hi! link rustDeriveTrait Red
hi! link rustStructure Orange
hi! link rustEnumVariant Purple
hi! link rustSelf Blue
hi! link rustPubScopeCrate Purple
hi! link rustSuper Purple
hi! link rustMacroVariable Purple
hi! link rustExternCrate Purple
hi! link rustFuncName Aqua
hi! link rustFuncCall Green
hi! link rustSigil Aqua
hi! link phpUseClass Green
hi! link phpUseAlias Aqua
hi! link phpParent White
hi! link phpFunction Aqua
hi! link phpMethod Green
hi! link phpVarSelector Aqua
hi! link phpUseNamespaceSeparator Aqua
hi! link phpMemberSelector Orange
hi! link phpClass Aqua
hi! link phpClassExtends Aqua
hi! link phpMethodsVar Green
hi! link phpStaticClasses Purple
hi! link csUnspecifiedStatement Purple
hi! link csStorage Red
hi! link csClass Red
hi! link csClassType Aqua
hi! link csType Orange
hi! link csNewType Yellow
hi! link csEndColon White
hi! link csBraces White
hi! link csParens White
hi! link csOpSymbols Orange
hi! link csLogicSymbols Aqua
hi! link csInterpolationDelimiter Aqua
hi! link csInterpolationFormat Blue
hi! link csInterpolationAlignDel Aqua
hi! link csInterpolationFormatDel Aqua
hi! link fsharpAttrib Purple
hi! link fsharpAttribute Purple
hi! link fsharpException Red
hi! link fsharpLabel Green
hi! link rubyModule Purple
hi! link rubyModuleName Orange
hi! link rubyClass Red
hi! link rubyClassName Aqua
hi! link rubyConstant Aqua
hi! link rubySymbol Blue
hi! link rubyDefine Orange
hi! link rubyPseudoVariable Yellow
hi! link rubyMethodName Green
hi! link rubyInterpolation Yellow
hi! link rubyInterpolationDelimiter Aqua
hi! link perlStatementPackage Purple
hi! link perlPackageDecl Aqua
hi! link perlStatementInclude Purple
hi! link perlStatementStorage Orange
hi! link perlStatementList Orange
hi! link perlMethod Green
hi! link perlVarPlain2 Aqua
hi! link perlVarSimpleMemberName Yellow
hi! link podCommand Orange
hi! link podCmdText Purple
hi! link podVerbatimLine Green
hi! link haskellDeclKeyword Red
hi! link haskellType Aqua
hi! link haskellPreProc Purple
hi! link haskellWhere Red
hi! link haskellParens Green
hi! link haskellDefault Red
hi! link luaLocal Orange
hi! link luaNoise Grey
hi! link luaFuncCall Green
hi! link luaFuncKeyword Red
hi! link luaConstant Aqua
hi! link luaSpecialValue Blue
hi! link moonLuaFunc Aqua
hi! link moonSpecialOp White
hi! link moonExtendedOp Orange
hi! link moonSpecialVar Purple
hi! link moonFunction Aqua
hi! link moonDotAccess Grey
hi! link moonObject Yellow
hi! link moonInterp Blue
hi! link moonInterpDelim Aqua
hi! link dImport Aqua
hi! link dStructure Red
hi! link dEnum Red
hi! link dScopeDecl Red
hi! link dAnnotation Blue
hi! link dAttribute Blue
hi! link paramlist Green
hi! link scalaNameDefinition Blue
hi! link scalaCapitalWord Green
hi! link scalaKeywordModifier Orange
hi! link scalaSpecial Purple
hi! link scalaInstanceDeclaration Aqua
hi! link scalaInterpolationB Blue
hi! link scalaParameterAnnotation Purple
hi! link elixirModuleDefine Purple
hi! link elixirModuleDeclaration Yellow
hi! link elixirAlias Aqua
hi! link elixirVariable Purple
hi! link elixirPseudoVariable Yellow
hi! link elixirMacroDeclaration Purple
hi! link elixirAtom Blue
hi! link elixirKeyword Orange
hi! link elixirBlockDefinition Red
hi! link elixirDefine Red
hi! link elixirPrivateDefine Red
hi! link elixirGuard Red
hi! link elixirPrivateGuard Red
hi! link elixirModuleDefine Red
hi! link elixirProtocolDefine Red
hi! link elixirImplDefine Red
hi! link elixirRecordDefine Red
hi! link elixirPrivateRecordDefine Red
hi! link elixirMacroDefine Red
hi! link elixirPrivateMacroDefine Red
hi! link elixirDelegateDefine Red
hi! link elixirOverridableDefine Red
hi! link elixirExceptionDefine Red
hi! link elixirCallbackDefine Red
hi! link elixirStructDefine Red
hi! link elixirExUnitMacro Red
hi! link ocamlModPath Green
hi! link ocamlFullMod Green
hi! link ocamlFuncWith White
hi! link ocamlWith White
hi! link ocamlModParam White
hi! link ocamlModParam1 White
hi! link ocamlKeyChar Grey
hi! link ocamlAnyVar Blue
hi! link ocamlEqual Orange
hi! link ocamlArrow Aqua
hi! link ocamlPpxEncl Orange
hi! link ocamlPpxIdentifier Blue
hi! link ocamlSigEncl Orange
hi! link ocamlStructEncl Aqua
hi! link clojureKeyword Orange
hi! link clojureDefine Red
hi! link clojureSpecial Red
hi! link clojureQuote Aqua
hi! link clojureUnquote Aqua
hi! link clojureException Red
hi! link clojureRegexp Aqua
hi! link clojureRegexpEscape Aqua
hi! link clojureVariable Blue
hi! link clojureMeta Yellow
hi! link clojureDeref Yellow
hi! link erlangLocalFuncCall Aqua
hi! link erlangType Orange
hi! link erlangGlobalFuncCall Green
hi! link erlangLocalFuncRef Yellow
hi! link erlangOperator White
hi! link erlangRecord Purple
hi! link plug2 Green
hi! link plugBracket Grey
hi! link plugName Aqua
hi! link plugDash Orange
hi! link plugError Red
hi! link plugNotLoaded Grey
hi! link plugRelDate Grey
hi! link plugH2 Orange
hi! link plugMessage Orange
hi! link plugStar Red
hi! link plugUpdate Blue
hi! link plugDeleted Grey
hi! link plugEdge Yellow
hi! link plugSha Green
hi! link EasyMotionTarget Search
hi! link EasyMotionShade Comment
hi! link Sneak Search
hi! link SneakLabel Search
hi! link gitcommitSelectedFile Green
hi! link gitcommitDiscardedFile Red
let g:fzf_colors = {
      \ 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Green'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Aqua'],
      \ 'info':    ['fg', 'Aqua'],
      \ 'prompt':  ['fg', 'Orange'],
      \ 'pointer': ['fg', 'Blue'],
      \ 'marker':  ['fg', 'Yellow'],
      \ 'spinner': ['fg', 'Yellow'],
      \ 'header':  ['fg', 'Grey']
      \ }
hi! link CtrlPNoEntries Red
hi! link CtrlPPrtCursor Blue
if !exists('g:Lf_StlColorscheme')
  let g:Lf_StlColorscheme = 'gruvbox_material'
endif
hi! link StartifyBracket Grey
hi! link StartifyFile White
hi! link StartifyNumber Red
hi! link StartifyPath Green
hi! link StartifySlash Aqua
hi! link StartifySection Blue
hi! link StartifyHeader Orange
hi! link StartifySpecial Grey
hi! link StartifyFooter Grey
hi! link DirvishPathTail Aqua
hi! link DirvishArg Yellow
hi! link netrwDir Green
hi! link netrwClassify Green
hi! link netrwLink Grey
hi! link netrwSymLink White
hi! link netrwExe Yellow
hi! link netrwComment Grey
hi! link netrwList Aqua
hi! link netrwHelpCmd Blue
hi! link netrwCmdSep LightGrey
hi! link netrwVersion Orange
hi! link NERDTreeDir Green
hi! link NERDTreeDirSlash Aqua
hi! link NERDTreeOpenable Orange
hi! link NERDTreeClosable Orange
hi! link NERDTreeFile White
hi! link NERDTreeExecFile Yellow
hi! link NERDTreeUp Grey
hi! link NERDTreeCWD Aqua
hi! link NERDTreeHelp LightGrey
hi! link NERDTreeToggleOn Green
hi! link NERDTreeToggleOff Red
hi! link NERDTreeFlags Orange
hi! link NERDTreeLinkFile Grey
hi! link NERDTreeLinkTarget Green
hi! link TagbarFoldIcon Green
hi! link TagbarSignature Green
hi! link TagbarKind Red
hi! link TagbarScope Orange
hi! link TagbarNestedKind Aqua
hi! link TagbarVisibilityPrivate Red
hi! link TagbarVisibilityPublic Blue
hi! link ALEVirtualTextError Grey
hi! link ALEVirtualTextWarning Grey
hi! link ALEVirtualTextInfo Grey
hi! link ALEVirtualTextStyleError ALEVirtualTextError
hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
hi! link CocCodeLens Grey
hi! link CocErrorSign ALEErrorSign
hi! link CocWarningSign ALEWarningSign
hi! link CocInfoSign ALEInfoSign
hi! link CocErrorHighlight ALEError
hi! link CocWarningHighlight ALEWarning
hi! link CocInfoHighlight ALEInfo
hi! link CocWarningVirtualText ALEVirtualTextWarning
hi! link CocErrorVirtualText ALEVirtualTextError
hi! link CocInfoVirtualText ALEVirtualTextInfo
hi! link CocHintVirtualText ALEVirtualTextInfo
hi! link CocCodeLens ALEVirtualTextInfo
hi! link QuickmenuOption Green
hi! link QuickmenuNumber Red
hi! link QuickmenuBracket Grey
hi! link QuickmenuHelp Green
hi! link QuickmenuSpecial Purple
hi! link QuickmenuHeader Orange
hi! link UndotreeNode Orange
hi! link UndotreeNodeCurrent Red
hi! link UndotreeSeq Green
hi! link UndotreeNext Blue
hi! link UndotreeTimeStamp Grey
hi! link UndotreeHead Yellow
hi! link UndotreeBranch Yellow
hi! link UndotreeCurrent Aqua
hi! link UndotreeSavedSmall Purple

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#665c54', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e', '#928374', '#ea6962',
        \ '#a9b665', '#e3a84e', '#7daea3', '#d3869b', '#89b482', '#dfbf8e']
  if has('nvim')
    let g:terminal_color_0 = '#665c54'
    let g:terminal_color_1 = '#ea6962'
    let g:terminal_color_2 = '#a9b665'
    let g:terminal_color_3 = '#e78a4e'
    let g:terminal_color_4 = '#7daea3'
    let g:terminal_color_5 = '#d3869b'
    let g:terminal_color_6 = '#89b482'
    let g:terminal_color_7 = '#dfbf8e'
    let g:terminal_color_8 = '#928374'
    let g:terminal_color_9 = '#ea6962'
    let g:terminal_color_10 = '#a9b665'
    let g:terminal_color_11 = '#e3a84e'
    let g:terminal_color_12 = '#7daea3'
    let g:terminal_color_13 = '#d3869b'
    let g:terminal_color_14 = '#89b482'
    let g:terminal_color_15 = '#dfbf8e'
  endif
  hi White guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LightGrey guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Orange guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Aqua guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Purple guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi WhiteBold guifg=#dfbf8e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi LightGreyBold guifg=#a89984 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi GreyBold guifg=#928374 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi RedBold guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi OrangeBold guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi YellowBold guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi GreenBold guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi AquaBold guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi BlueBold guifg=#7daea3 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi PurpleBold guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  else
    hi WhiteBold guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi LightGreyBold guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi GreyBold guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi RedBold guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi OrangeBold guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi YellowBold guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi GreenBold guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi AquaBold guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi BlueBold guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PurpleBold guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
  if get(g:, 'gruvbox_material_hard_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#dfbf8e guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#dfbf8e guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#7c6f64 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#32361a guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#0d3138 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#3c1f1e guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#1d2021 guisp=NONE gui=reverse cterm=reverse
  hi Directory guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#1d2021 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#1d2021 guibg=#a89984 guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#928374 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#928374 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=NONE guisp=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search guifg=NONE guibg=NONE guisp=NONE gui=reverse,underline ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#dfbf8e guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#7c6f64 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#ea6962 guibg=NONE guisp=#ea6962 gui=italic,undercurl cterm=italic,undercurl
  hi SpellCap guifg=#7daea3 guibg=NONE guisp=#7daea3 gui=italic,undercurl cterm=italic,undercurl
  hi SpellLocal guifg=#89b482 guibg=NONE guisp=#89b482 gui=italic,undercurl cterm=italic,undercurl
  hi SpellRare guifg=#d3869b guibg=NONE guisp=#d3869b gui=italic,undercurl cterm=italic,undercurl
  hi StatusLine guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#a89984 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#a89984 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#dfbf8e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#665c54 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#928374 guibg=NONE guisp=NONE gui=bold,italic cterm=bold,italic
  hi CursorIM guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine guifg=NONE guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=bold cterm=bold
  hi QuickFixLine guifg=#e3a84e guibg=#1d2021 guisp=NONE gui=reverse cterm=reverse
  hi Debug guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Label guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#7daea3 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SpecialKey guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Delimiter guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=NONE guibg=#3c1f1e guisp=NONE gui=NONE cterm=NONE
  hi markdownH1 guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH2 guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH3 guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH4 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownUrl guifg=#7daea3 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi mkdURL guifg=#7daea3 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdInlineURL guifg=#d3869b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdItalic guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi rstStandaloneHyperlink guifg=#d3869b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi htmlH1 guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH2 guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH3 guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH4 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic,underline ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi plug1 guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi plugNumber guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi SpellBad gui=undercurl cterm=undercurl
    hi SpellCap gui=undercurl cterm=undercurl
    hi SpellLocal gui=undercurl cterm=undercurl
    hi SpellRare gui=undercurl cterm=undercurl
    hi Todo gui=bold cterm=bold
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi markdownItalicDelimiter gui=NONE cterm=NONE
    hi mkdItalic gui=NONE cterm=NONE
    hi htmlBoldItalic gui=bold cterm=bold
    hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
    hi htmlUnderlineItalic gui=underline cterm=underline
    hi htmlItalic gui=NONE cterm=NONE
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd guifg=#1d2021 guibg=#504945 guisp=NONE gui=reverse cterm=reverse
      hi IndentGuidesEven guifg=#1d2021 guibg=#3c3836 guisp=NONE gui=reverse cterm=reverse
    else
      hi IndentGuidesOdd guifg=#1d2021 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
      hi IndentGuidesEven guifg=#1d2021 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd guifg=#a9b665 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#d3869b guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#a9b665 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticError guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticWarning guifg=NONE guibg=NONE guisp=#e3a84e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticErrorSign guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticWarningSign guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignatureMarkText guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignatureMarkerText guifg=#d3869b guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLl guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLu guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLo guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLm guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CtrlPMatch guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi CtrlPPrtBase guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CtrlPLinePre guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CtrlPMode1 guifg=#7daea3 guibg=#504945 guisp=NONE gui=bold cterm=bold
  hi CtrlPMode2 guifg=#1d2021 guibg=#7daea3 guisp=NONE gui=bold cterm=bold
  hi CtrlPStats guifg=#a89984 guibg=#504945 guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match0 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match1 guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match2 guifg=#7daea3 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match3 guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match4 guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_matchRefine guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineActive guifg=#a89984 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineHidden guifg=#7c6f64 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineFill guifg=#1d2021 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEWarning guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEInfo guifg=NONE guibg=NONE guisp=#7daea3 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEErrorSign guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi multiple_cursors_cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign guifg=#89b482 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi White ctermfg=223 ctermbg=NONE cterm=NONE
  hi LightGrey ctermfg=246 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=245 ctermbg=NONE cterm=NONE
  hi Red ctermfg=167 ctermbg=NONE cterm=NONE
  hi Orange ctermfg=208 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=214 ctermbg=NONE cterm=NONE
  hi Green ctermfg=142 ctermbg=NONE cterm=NONE
  hi Aqua ctermfg=108 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=109 ctermbg=NONE cterm=NONE
  hi Purple ctermfg=175 ctermbg=NONE cterm=NONE
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi WhiteBold ctermfg=223 ctermbg=NONE cterm=bold
    hi LightGreyBold ctermfg=246 ctermbg=NONE cterm=bold
    hi GreyBold ctermfg=245 ctermbg=NONE cterm=bold
    hi RedBold ctermfg=167 ctermbg=NONE cterm=bold
    hi OrangeBold ctermfg=208 ctermbg=NONE cterm=bold
    hi YellowBold ctermfg=214 ctermbg=NONE cterm=bold
    hi GreenBold ctermfg=142 ctermbg=NONE cterm=bold
    hi AquaBold ctermfg=108 ctermbg=NONE cterm=bold
    hi BlueBold ctermfg=109 ctermbg=NONE cterm=bold
    hi PurpleBold ctermfg=175 ctermbg=NONE cterm=bold
  else
    hi WhiteBold ctermfg=223 ctermbg=NONE cterm=NONE
    hi LightGreyBold ctermfg=246 ctermbg=NONE cterm=NONE
    hi GreyBold ctermfg=245 ctermbg=NONE cterm=NONE
    hi RedBold ctermfg=167 ctermbg=NONE cterm=NONE
    hi OrangeBold ctermfg=208 ctermbg=NONE cterm=NONE
    hi YellowBold ctermfg=214 ctermbg=NONE cterm=NONE
    hi GreenBold ctermfg=142 ctermbg=NONE cterm=NONE
    hi AquaBold ctermfg=108 ctermbg=NONE cterm=NONE
    hi BlueBold ctermfg=109 ctermbg=NONE cterm=NONE
    hi PurpleBold ctermfg=175 ctermbg=NONE cterm=NONE
  endif
  if get(g:, 'gruvbox_material_hard_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=234 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=109 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLineNr ctermfg=214 ctermbg=237 cterm=NONE
  hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=52 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=234 cterm=reverse
  hi Directory ctermfg=142 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=234 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=234 ctermbg=246 cterm=bold
  hi MoreMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=245 ctermbg=237 cterm=NONE
  hi Folded ctermfg=245 ctermbg=237 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=239 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
  hi PmenuSel ctermfg=234 ctermbg=246 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
  hi Question ctermfg=208 ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=109 ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=108 ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=175 ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=223 ctermbg=241 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=237 cterm=NONE
  hi StatusLineTerm ctermfg=223 ctermbg=241 cterm=NONE
  hi StatusLineTermNC ctermfg=246 ctermbg=237 cterm=NONE
  hi TabLine ctermfg=223 ctermbg=241 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=234 ctermbg=246 cterm=NONE
  hi VertSplit ctermfg=241 ctermbg=234 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=234 ctermbg=246 cterm=NONE
  hi Todo ctermfg=245 ctermbg=NONE cterm=bold,italic
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=241 cterm=NONE
  hi ToolbarButton ctermfg=223 ctermbg=241 cterm=bold
  hi QuickFixLine ctermfg=214 ctermbg=234 cterm=reverse
  hi Debug ctermfg=208 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=167 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=167 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=167 ctermbg=NONE cterm=NONE
  hi Title ctermfg=208 ctermbg=NONE cterm=bold
  hi Label ctermfg=208 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=208 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=208 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=214 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=214 ctermbg=NONE cterm=NONE
  hi Special ctermfg=214 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=214 ctermbg=NONE cterm=NONE
  hi String ctermfg=142 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=142 ctermbg=NONE cterm=NONE
  hi Character ctermfg=142 ctermbg=NONE cterm=NONE
  hi Number ctermfg=142 ctermbg=NONE cterm=NONE
  hi Float ctermfg=142 ctermbg=NONE cterm=NONE
  hi Define ctermfg=108 ctermbg=NONE cterm=NONE
  hi Function ctermfg=108 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=108 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=175 ctermbg=NONE cterm=NONE
  hi Include ctermfg=175 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=175 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=175 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=109 ctermbg=NONE cterm=underline
  hi SpecialKey ctermfg=109 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=245 ctermbg=NONE cterm=italic
  hi Delimiter ctermfg=223 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=223 ctermbg=NONE cterm=NONE
  hi Error ctermfg=NONE ctermbg=52 cterm=NONE
  hi markdownH1 ctermfg=208 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=214 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=108 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=142 ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=109 ctermbg=NONE cterm=underline
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter ctermfg=245 ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=109 ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=175 ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=245 ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=175 ctermbg=NONE cterm=underline
  hi htmlH1 ctermfg=208 ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=214 ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=108 ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=142 ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi plug1 ctermfg=175 ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=108 ctermbg=NONE cterm=bold
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Todo cterm=bold
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd ctermfg=234 ctermbg=239 cterm=reverse
      hi IndentGuidesEven ctermfg=234 ctermbg=237 cterm=reverse
    else
      hi IndentGuidesOdd ctermfg=234 ctermbg=239 cterm=NONE
      hi IndentGuidesEven ctermfg=234 ctermbg=237 cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd ctermfg=142 ctermbg=237 cterm=NONE
  hi GitGutterChange ctermfg=214 ctermbg=237 cterm=NONE
  hi GitGutterDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi GitGutterChangeDelete ctermfg=175 ctermbg=237 cterm=NONE
  hi SignifySignAdd ctermfg=142 ctermbg=237 cterm=NONE
  hi SignifySignChange ctermfg=214 ctermbg=237 cterm=NONE
  hi SignifySignDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=167 ctermbg=237 cterm=NONE
  hi SyntasticWarningSign ctermfg=214 ctermbg=237 cterm=NONE
  hi SignatureMarkText ctermfg=109 ctermbg=237 cterm=NONE
  hi SignatureMarkerText ctermfg=175 ctermbg=237 cterm=NONE
  hi ShowMarksHLl ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLu ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLo ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLm ctermfg=109 ctermbg=237 cterm=NONE
  hi CtrlPMatch ctermfg=142 ctermbg=NONE cterm=bold
  hi CtrlPPrtBase ctermfg=239 ctermbg=NONE cterm=NONE
  hi CtrlPLinePre ctermfg=239 ctermbg=NONE cterm=NONE
  hi CtrlPMode1 ctermfg=109 ctermbg=239 cterm=bold
  hi CtrlPMode2 ctermfg=234 ctermbg=109 cterm=bold
  hi CtrlPStats ctermfg=246 ctermbg=239 cterm=bold
  hi Lf_hl_match ctermfg=142 ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=142 ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=108 ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=109 ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=175 ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=208 ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=167 ctermbg=NONE cterm=bold
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent ctermfg=234 ctermbg=246 cterm=NONE
  hi BufTabLineActive ctermfg=246 ctermbg=239 cterm=NONE
  hi BufTabLineHidden ctermfg=243 ctermbg=237 cterm=NONE
  hi BufTabLineFill ctermfg=234 ctermbg=234 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=167 ctermbg=237 cterm=NONE
  hi ALEWarningSign ctermfg=214 ctermbg=237 cterm=NONE
  hi ALEInfoSign ctermfg=109 ctermbg=237 cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=239 cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=108 ctermbg=237 cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=175 ctermbg=NONE cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'gruvbox_material_hard_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=Black cterm=reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=bold
  hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=Blue ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi StatusLineTerm ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineTermNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Todo ctermfg=Grey ctermbg=NONE cterm=bold,italic
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=DarkGrey cterm=bold
  hi QuickFixLine ctermfg=Yellow ctermbg=Black cterm=reverse
  hi Debug ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Tag ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Include ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi markdownH1 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=Green ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=Blue ctermbg=NONE cterm=underline
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter ctermfg=Grey ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=Blue ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=Magenta ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=Grey ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=Magenta ctermbg=NONE cterm=underline
  hi htmlH1 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=Green ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi plug1 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=Cyan ctermbg=NONE cterm=bold
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Todo cterm=bold
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd ctermfg=Black ctermbg=DarkGrey cterm=reverse
      hi IndentGuidesEven ctermfg=Black ctermbg=DarkGrey cterm=reverse
    else
      hi IndentGuidesOdd ctermfg=Black ctermbg=DarkGrey cterm=NONE
      hi IndentGuidesEven ctermfg=Black ctermbg=DarkGrey cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi GitGutterChange ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi SignifySignAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi SignifySignChange ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi SyntasticWarningSign ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi SignatureMarkText ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi SignatureMarkerText ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLl ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLu ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLo ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLm ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi CtrlPMatch ctermfg=Green ctermbg=NONE cterm=bold
  hi CtrlPPrtBase ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi CtrlPLinePre ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi CtrlPMode1 ctermfg=Blue ctermbg=DarkGrey cterm=bold
  hi CtrlPMode2 ctermfg=Black ctermbg=Blue cterm=bold
  hi CtrlPStats ctermfg=LightGrey ctermbg=DarkGrey cterm=bold
  hi Lf_hl_match ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=Blue ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=Red ctermbg=NONE cterm=bold
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi BufTabLineActive ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi BufTabLineHidden ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi BufTabLineFill ctermfg=Black ctermbg=Black cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=Magenta ctermbg=NONE cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:             dark
" Color: dark0            #1d2021         234             Black
" Color: dark1            #3c3836         237             DarkGrey
" Color: dark2            #504945         239             DarkGrey
" Color: dark3            #665c54         241             DarkGrey
" Color: dark4            #7c6f64         243             DarkGrey
" Color: grey             #928374         245             Grey
" Color: lightgrey        #a89984         246             LightGrey
" Color: light            #dfbf8e         223             White
" Color: red              #ea6962         167             Red
" Color: orange           #e78a4e         208             DarkYellow
" Color: yellow           #e3a84e         214             Yellow
" Color: green            #a9b665         142             Green
" Color: aqua             #89b482         108             Cyan
" Color: blue             #7daea3         109             Blue
" Color: purple           #d3869b         175             Magenta
" Color: darkgreen        #32361a         ~               DarkGreen
" Color: darkred          #3c1f1e         ~               DarkRed
" Color: darkblue         #0d3138         ~               DarkBlue
" Term colors: dark3 red green orange blue purple aqua light
" Term colors: grey red green yellow blue purple aqua light
" vim: et ts=2 sw=2
